// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsStaticWebsite
{
    [AwsStaticWebsiteResourceType("aws-static-website:index:PublicBucketPolicy")]
    public partial class PublicBucketPolicy : global::Pulumi.ComponentResource
    {
        [Output("ownershipControls")]
        public Output<Pulumi.Aws.S3.BucketOwnershipControls> OwnershipControls { get; private set; } = null!;

        [Output("publicAccessBlock")]
        public Output<Pulumi.Aws.S3.BucketPublicAccessBlock> PublicAccessBlock { get; private set; } = null!;


        /// <summary>
        /// Create a PublicBucketPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PublicBucketPolicy(string name, PublicBucketPolicyArgs args, ComponentResourceOptions? options = null)
            : base("aws-static-website:index:PublicBucketPolicy", name, args ?? new PublicBucketPolicyArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class PublicBucketPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The bucket to apply the public policy to.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<Pulumi.Aws.S3.Bucket> Bucket { get; set; } = null!;

        public PublicBucketPolicyArgs()
        {
        }
        public static new PublicBucketPolicyArgs Empty => new PublicBucketPolicyArgs();
    }
}
