# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'AtomicDeploymentArgsArgs',
]

@pulumi.input_type
class AtomicDeploymentArgsArgs:
    def __init__(__self__, *,
                 pulumi_organization: Optional[pulumi.Input[str]] = None):
        """
        :param pulumi.Input[str] pulumi_organization: The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
        """
        if pulumi_organization is not None:
            pulumi.set(__self__, "pulumi_organization", pulumi_organization)

    @property
    @pulumi.getter(name="pulumiOrganization")
    def pulumi_organization(self) -> Optional[pulumi.Input[str]]:
        """
        The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
        """
        return pulumi.get(self, "pulumi_organization")

    @pulumi_organization.setter
    def pulumi_organization(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "pulumi_organization", value)


