// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awsstaticwebsite

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AtomicDeploymentArgs struct {
	// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
	PulumiOrganization *string `pulumi:"pulumiOrganization"`
}

// AtomicDeploymentArgsInput is an input type that accepts AtomicDeploymentArgsArgs and AtomicDeploymentArgsOutput values.
// You can construct a concrete instance of `AtomicDeploymentArgsInput` via:
//
//          AtomicDeploymentArgsArgs{...}
type AtomicDeploymentArgsInput interface {
	pulumi.Input

	ToAtomicDeploymentArgsOutput() AtomicDeploymentArgsOutput
	ToAtomicDeploymentArgsOutputWithContext(context.Context) AtomicDeploymentArgsOutput
}

type AtomicDeploymentArgsArgs struct {
	// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
	PulumiOrganization pulumi.StringPtrInput `pulumi:"pulumiOrganization"`
}

func (AtomicDeploymentArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AtomicDeploymentArgs)(nil)).Elem()
}

func (i AtomicDeploymentArgsArgs) ToAtomicDeploymentArgsOutput() AtomicDeploymentArgsOutput {
	return i.ToAtomicDeploymentArgsOutputWithContext(context.Background())
}

func (i AtomicDeploymentArgsArgs) ToAtomicDeploymentArgsOutputWithContext(ctx context.Context) AtomicDeploymentArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AtomicDeploymentArgsOutput)
}

func (i AtomicDeploymentArgsArgs) ToAtomicDeploymentArgsPtrOutput() AtomicDeploymentArgsPtrOutput {
	return i.ToAtomicDeploymentArgsPtrOutputWithContext(context.Background())
}

func (i AtomicDeploymentArgsArgs) ToAtomicDeploymentArgsPtrOutputWithContext(ctx context.Context) AtomicDeploymentArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AtomicDeploymentArgsOutput).ToAtomicDeploymentArgsPtrOutputWithContext(ctx)
}

// AtomicDeploymentArgsPtrInput is an input type that accepts AtomicDeploymentArgsArgs, AtomicDeploymentArgsPtr and AtomicDeploymentArgsPtrOutput values.
// You can construct a concrete instance of `AtomicDeploymentArgsPtrInput` via:
//
//          AtomicDeploymentArgsArgs{...}
//
//  or:
//
//          nil
type AtomicDeploymentArgsPtrInput interface {
	pulumi.Input

	ToAtomicDeploymentArgsPtrOutput() AtomicDeploymentArgsPtrOutput
	ToAtomicDeploymentArgsPtrOutputWithContext(context.Context) AtomicDeploymentArgsPtrOutput
}

type atomicDeploymentArgsPtrType AtomicDeploymentArgsArgs

func AtomicDeploymentArgsPtr(v *AtomicDeploymentArgsArgs) AtomicDeploymentArgsPtrInput {
	return (*atomicDeploymentArgsPtrType)(v)
}

func (*atomicDeploymentArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AtomicDeploymentArgs)(nil)).Elem()
}

func (i *atomicDeploymentArgsPtrType) ToAtomicDeploymentArgsPtrOutput() AtomicDeploymentArgsPtrOutput {
	return i.ToAtomicDeploymentArgsPtrOutputWithContext(context.Background())
}

func (i *atomicDeploymentArgsPtrType) ToAtomicDeploymentArgsPtrOutputWithContext(ctx context.Context) AtomicDeploymentArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AtomicDeploymentArgsPtrOutput)
}

type AtomicDeploymentArgsOutput struct{ *pulumi.OutputState }

func (AtomicDeploymentArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AtomicDeploymentArgs)(nil)).Elem()
}

func (o AtomicDeploymentArgsOutput) ToAtomicDeploymentArgsOutput() AtomicDeploymentArgsOutput {
	return o
}

func (o AtomicDeploymentArgsOutput) ToAtomicDeploymentArgsOutputWithContext(ctx context.Context) AtomicDeploymentArgsOutput {
	return o
}

func (o AtomicDeploymentArgsOutput) ToAtomicDeploymentArgsPtrOutput() AtomicDeploymentArgsPtrOutput {
	return o.ToAtomicDeploymentArgsPtrOutputWithContext(context.Background())
}

func (o AtomicDeploymentArgsOutput) ToAtomicDeploymentArgsPtrOutputWithContext(ctx context.Context) AtomicDeploymentArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AtomicDeploymentArgs) *AtomicDeploymentArgs {
		return &v
	}).(AtomicDeploymentArgsPtrOutput)
}

// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
func (o AtomicDeploymentArgsOutput) PulumiOrganization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AtomicDeploymentArgs) *string { return v.PulumiOrganization }).(pulumi.StringPtrOutput)
}

type AtomicDeploymentArgsPtrOutput struct{ *pulumi.OutputState }

func (AtomicDeploymentArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AtomicDeploymentArgs)(nil)).Elem()
}

func (o AtomicDeploymentArgsPtrOutput) ToAtomicDeploymentArgsPtrOutput() AtomicDeploymentArgsPtrOutput {
	return o
}

func (o AtomicDeploymentArgsPtrOutput) ToAtomicDeploymentArgsPtrOutputWithContext(ctx context.Context) AtomicDeploymentArgsPtrOutput {
	return o
}

func (o AtomicDeploymentArgsPtrOutput) Elem() AtomicDeploymentArgsOutput {
	return o.ApplyT(func(v *AtomicDeploymentArgs) AtomicDeploymentArgs {
		if v != nil {
			return *v
		}
		var ret AtomicDeploymentArgs
		return ret
	}).(AtomicDeploymentArgsOutput)
}

// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
func (o AtomicDeploymentArgsPtrOutput) PulumiOrganization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AtomicDeploymentArgs) *string {
		if v == nil {
			return nil
		}
		return v.PulumiOrganization
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AtomicDeploymentArgsInput)(nil)).Elem(), AtomicDeploymentArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AtomicDeploymentArgsPtrInput)(nil)).Elem(), AtomicDeploymentArgsArgs{})
	pulumi.RegisterOutputType(AtomicDeploymentArgsOutput{})
	pulumi.RegisterOutputType(AtomicDeploymentArgsPtrOutput{})
}
