// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awsstaticwebsite

type AtomicDeploymentArgs struct {
	// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
	PulumiOrganization *string `pulumi:"pulumiOrganization"`
}

func init() {
}
