// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AtomicDeploymentArgsArgs {
    /**
     * The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
     */
    pulumiOrganization?: pulumi.Input<string>;
}
