// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsStaticWebsite.Inputs
{

    public sealed class AtomicDeploymentArgsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Pulumi Organization you are deploying the website with. You only need to set this option if you are using an Organization in the Pulumi Service.
        /// </summary>
        [Input("pulumiOrganization")]
        public Input<string>? PulumiOrganization { get; set; }

        public AtomicDeploymentArgsArgs()
        {
        }
    }
}
