// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsStaticWebsite.Inputs
{

    public sealed class CDNArgsArgs : Pulumi.ResourceArgs
    {
        [Input("cloudfrontFunctionAssociations")]
        private InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs>? _cloudfrontFunctionAssociations;

        /// <summary>
        /// A config block that triggers a cloudfront
        /// function with specific actions.
        /// </summary>
        public InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs> CloudfrontFunctionAssociations
        {
            get => _cloudfrontFunctionAssociations ?? (_cloudfrontFunctionAssociations = new InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs>());
            set => _cloudfrontFunctionAssociations = value;
        }

        /// <summary>
        /// The forwarded values configuration that specifies how CloudFront handles query strings, cookies and headers.
        /// </summary>
        [Input("forwardedValues")]
        public Input<Pulumi.Aws.CloudFront.Inputs.DistributionDefaultCacheBehaviorForwardedValuesArgs>? ForwardedValues { get; set; }

        [Input("lambdaFunctionAssociations")]
        private InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs>? _lambdaFunctionAssociations;

        /// <summary>
        /// A config block that triggers a lambda
        /// function with specific actions.
        /// </summary>
        public InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs> LambdaFunctionAssociations
        {
            get => _lambdaFunctionAssociations ?? (_lambdaFunctionAssociations = new InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs>());
            set => _lambdaFunctionAssociations = value;
        }

        public CDNArgsArgs()
        {
        }
    }
}
