// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsStaticWebsite.Inputs
{

    public sealed class CDNArgsArgs : Pulumi.ResourceArgs
    {
        [Input("cloudfrontFunctions")]
        private InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs>? _cloudfrontFunctions;

        /// <summary>
        /// A config block that triggers a cloudfront
        /// function with specific actions.
        /// </summary>
        public InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs> CloudfrontFunctions
        {
            get => _cloudfrontFunctions ?? (_cloudfrontFunctions = new InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorFunctionAssociationArgs>());
            set => _cloudfrontFunctions = value;
        }

        /// <summary>
        /// The forwarded values configuration that specifies how CloudFront handles query strings, cookies and headers.
        /// </summary>
        [Input("forwardedValues")]
        public Input<Pulumi.Aws.CloudFront.Inputs.DistributionDefaultCacheBehaviorForwardedValuesArgs>? ForwardedValues { get; set; }

        [Input("lambdaFunctions")]
        private InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs>? _lambdaFunctions;

        /// <summary>
        /// A config block that triggers a lambda
        /// function with specific actions.
        /// </summary>
        public InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs> LambdaFunctions
        {
            get => _lambdaFunctions ?? (_lambdaFunctions = new InputList<Pulumi.Aws.CloudFront.Inputs.DistributionOrderedCacheBehaviorLambdaFunctionAssociationArgs>());
            set => _lambdaFunctions = value;
        }

        public CDNArgsArgs()
        {
        }
    }
}
