// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

export class PublicBucketPolicy extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'aws-static-website:index:PublicBucketPolicy';

    /**
     * Returns true if the given object is an instance of PublicBucketPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PublicBucketPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PublicBucketPolicy.__pulumiType;
    }

    public /*out*/ readonly ownershipControls!: pulumi.Output<pulumiAws.s3.BucketOwnershipControls>;
    public /*out*/ readonly publicAccessBlock!: pulumi.Output<pulumiAws.s3.BucketPublicAccessBlock>;

    /**
     * Create a PublicBucketPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PublicBucketPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.bucket === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucket'");
            }
            resourceInputs["bucket"] = args ? args.bucket : undefined;
            resourceInputs["ownershipControls"] = undefined /*out*/;
            resourceInputs["publicAccessBlock"] = undefined /*out*/;
        } else {
            resourceInputs["ownershipControls"] = undefined /*out*/;
            resourceInputs["publicAccessBlock"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PublicBucketPolicy.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a PublicBucketPolicy resource.
 */
export interface PublicBucketPolicyArgs {
    /**
     * The bucket to apply the public policy to.
     */
    bucket: pulumi.Input<pulumiAws.s3.Bucket>;
}
